name: Testes da API

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pytest:
    name: Rodar testes Python
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Rodar testes
        run: |
          python -m pytest -q --tb=short --disable-warnings
